language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/kujua-docs
  - npm install kanso -g

script: ./scripts/ci/run_build.sh

after_success:
  - bash ./scripts/ci/after_success.sh

notifications:
  email:
    - dev@medicmobile.org
